[package]
name = "server"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1.0.104"
axum = { version = "0.8.9", features = ["multipart"] }
email_address = "0.2.9"
authorizer = { path = "../authorizer" }
cache = { path = "../cache" }
database = { path = "../database" }
emailer = { path = "../emailer" }
common = { path = "../common" }
searcher = { path = "../searcher" }
semver = "1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
time = { version = "0.3.55", features = ["formatting"] }
tokio = { version = "1.53.1", features = ["macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
tokio-util = { version = "0.7.19", features = ["io"] }
toml = "1.1.4"
tower-http = { version = "0.7.0", features = ["trace"] }
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.24.0", features = ["serde", "v7"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["io-util"] }
tower = { version = "0.5.3", features = ["util"] }

[lints]
workspace = true
