[plugins.forFront]
category = "directory"
index = "index.html"
path = "/home/qkun/nail/code/front/dist"
step = "request"

[plugins.rateLimit]
category = "limit"
interval = "1s"
max = 32
tag = "ip"
type = "rate"
