[servers.nail]
access_log = "/home/qkun/nail/log/proxy/access.log?rolling=daily {when} {client_ip} {method} {uri} {proto} {status} {latency_human}"
addr = "127.0.0.1:8080"
locations = [
    "back_api",
    "front",
]
