
#[path = "context.rs"]
pub mod context;

#[path = "http/article.rs"]
pub mod http_article;
#[path = "http/article_delete.rs"]
pub mod http_article_delete;
#[path = "http/article_pdf.rs"]
pub mod http_article_pdf;
#[path = "http/article_search.rs"]
pub mod http_article_search;
#[path = "http/article_update.rs"]
pub mod http_article_update;
#[path = "http/authenticate.rs"]
pub mod http_authenticate;
#[path = "http/author.rs"]
pub mod http_author;
#[path = "http/comment.rs"]
pub mod http_comment;
#[path = "http/comment_delete.rs"]
pub mod http_comment_delete;
#[path = "http/contract.rs"]
pub mod http_contract;
#[path = "http/download.rs"]
pub mod http_download;
#[path = "http/email.rs"]
pub mod http_email;
#[path = "http/meta.rs"]
pub mod http_meta;
#[path = "http/user.rs"]
pub mod http_user;
#[path = "http/version.rs"]
pub mod http_version;

#[path = "http/proxy_and_attachment.rs"]
pub mod http_proxy_and_attachment;

#[path = "logic/article.rs"]
pub mod logic_article;
#[path = "logic/article_search.rs"]
pub mod logic_article_search;
#[path = "logic/authenticate.rs"]
pub mod logic_authenticate;
#[path = "logic/author.rs"]
pub mod logic_author;
#[path = "logic/comment.rs"]
pub mod logic_comment;
#[path = "logic/download.rs"]
pub mod logic_download;
#[path = "logic/email.rs"]
pub mod logic_email;
#[path = "logic/email_service.rs"]
pub mod logic_email_service;
#[path = "logic/user.rs"]
pub mod logic_user;
#[path = "logic/version.rs"]
pub mod logic_version;

#[path = "logic/concurrency.rs"]
pub mod logic_concurrency;

#[path = "repository/article.rs"]
pub mod repository_article;
#[path = "repository/authorization.rs"]
pub mod repository_authorization;
#[path = "repository/comment.rs"]
pub mod repository_comment;
#[path = "repository/db.rs"]
pub mod repository_db;
#[path = "repository/schema.rs"]
pub mod repository_schema;
#[path = "repository/search.rs"]
pub mod repository_search;
#[path = "repository/tag.rs"]
pub mod repository_tag;
#[path = "repository/token.rs"]
pub mod repository_token;
#[path = "repository/token_ttl.rs"]
pub mod repository_token_ttl;
#[path = "repository/transfer.rs"]
pub mod repository_transfer;
#[path = "repository/types.rs"]
pub mod repository_types;
#[path = "repository/user.rs"]
pub mod repository_user;

#[path = "configuration/mirror_consistency.rs"]
pub mod configuration_mirror_consistency;
#[path = "configuration/validation.rs"]
pub mod configuration_validation;
#[path = "log/rotation.rs"]
pub mod log_rotation;
#[path = "pdf/validation.rs"]
pub mod pdf_validation;
