use crate::repository::role::{
    PERMISSION_ARTICLE_CREATE, PERMISSION_ARTICLE_DELETE_HARD, PERMISSION_ARTICLE_DELETE_SOFT,
    PERMISSION_ARTICLE_DELETE_TRANSFER, PERMISSION_ARTICLE_READ, PERMISSION_ARTICLE_UNDELETE_SOFT,
    PERMISSION_ARTICLE_UPDATE, PERMISSION_COMMENT_CREATE, PERMISSION_COMMENT_DELETE_HARD,
    PERMISSION_COMMENT_DELETE_SOFT, PERMISSION_COMMENT_DELETE_TRANSFER, PERMISSION_COMMENT_READ,
    PERMISSION_COMMENT_UNDELETE_SOFT, PERMISSION_COMMENT_UPDATE, PERMISSION_ROLE_MANAGE,
    PERMISSION_ROLE_REVOKE, PERMISSION_USER_DELETE_HARD, PERMISSION_USER_READ,
    PERMISSION_USER_UPDATE, PERMISSION_VERSION_CREATE, PERMISSION_VERSION_DELETE_HARD,
    PERMISSION_VERSION_DELETE_SOFT, PERMISSION_VERSION_READ, PERMISSION_VERSION_UNDELETE_SOFT,
    PERMISSION_VERSION_UPDATE,
};

include!(concat!(env!("OUT_DIR"), "/routes.rs"));

pub const ROUTE_ACTIONS: &[(&str, &[&str])] = &[
    (ROUTE_CHALLENGE_CREATE, &[]),
    (ROUTE_CONFIG_READ, &[]),
    (ROUTE_TOKEN_CREATE, &[]),
    (ROUTE_USER_CREATE, &[]),
    (ROUTE_SESSION_READ, &[]),
    (ROUTE_SESSION_DELETE, &[]),
    (ROUTE_USER_ID_READ, &[PERMISSION_USER_READ]),
    (ROUTE_USER_ID_UPDATE, &[PERMISSION_USER_UPDATE]),
    (ROUTE_USER_ID_DELETE, &[PERMISSION_USER_DELETE_HARD]),
    (ROUTE_ARTICLE_READ, &[PERMISSION_ARTICLE_READ]),
    (ROUTE_ARTICLE_CREATE, &[PERMISSION_ARTICLE_CREATE]),
    (ROUTE_ARTICLE_ID_READ, &[PERMISSION_ARTICLE_READ]),
    (ROUTE_ARTICLE_ID_UPDATE, &[PERMISSION_ARTICLE_UPDATE]),
    (
        ROUTE_ARTICLE_ID_DELETE,
        &[
            PERMISSION_ARTICLE_DELETE_HARD,
            PERMISSION_ARTICLE_DELETE_TRANSFER,
            PERMISSION_ARTICLE_DELETE_SOFT,
        ],
    ),
    (
        ROUTE_ARTICLE_ID_UNDELETE_SOFT,
        &[PERMISSION_ARTICLE_UNDELETE_SOFT],
    ),
    (
        ROUTE_ARTICLE_ID_VERSION_CREATE,
        &[PERMISSION_VERSION_CREATE],
    ),
    (ROUTE_ARTICLE_ID_VERSION_READ, &[PERMISSION_VERSION_READ]),
    (
        ROUTE_ARTICLE_ID_VERSION_VERSION_ID_CONTENT_READ,
        &[PERMISSION_VERSION_READ],
    ),
    (ROUTE_VERSION_ID_READ, &[PERMISSION_VERSION_READ]),
    (ROUTE_VERSION_ID_UPDATE, &[PERMISSION_VERSION_UPDATE]),
    (
        ROUTE_VERSION_ID_DELETE,
        &[
            PERMISSION_VERSION_DELETE_SOFT,
            PERMISSION_VERSION_DELETE_HARD,
        ],
    ),
    (
        ROUTE_VERSION_ID_UNDELETE_SOFT,
        &[PERMISSION_VERSION_UNDELETE_SOFT],
    ),
    (
        ROUTE_VERSION_ID_COMMENTS_CREATE,
        &[PERMISSION_COMMENT_CREATE],
    ),
    (
        ROUTE_COMMENTS_ID_REPLIES_CREATE,
        &[PERMISSION_COMMENT_CREATE],
    ),
    (ROUTE_VERSION_ID_COMMENTS_READ, &[PERMISSION_COMMENT_READ]),
    (ROUTE_COMMENT_ID_READ, &[PERMISSION_COMMENT_READ]),
    (ROUTE_COMMENT_ID_REPLIES_READ, &[PERMISSION_COMMENT_READ]),
    (ROUTE_COMMENT_ID_UPDATE, &[PERMISSION_COMMENT_UPDATE]),
    (
        ROUTE_COMMENT_ID_DELETE,
        &[
            PERMISSION_COMMENT_DELETE_HARD,
            PERMISSION_COMMENT_DELETE_TRANSFER,
            PERMISSION_COMMENT_DELETE_SOFT,
        ],
    ),
    (
        ROUTE_COMMENT_ID_UNDELETE_SOFT,
        &[PERMISSION_COMMENT_UNDELETE_SOFT],
    ),
    (ROUTE_ROLE_CREATE, &[PERMISSION_ROLE_MANAGE]),
    (ROUTE_ROLE_READ, &[PERMISSION_ROLE_MANAGE]),
    (ROUTE_ROLE_NAME_READ, &[PERMISSION_ROLE_MANAGE]),
    (
        ROUTE_ROLE_NAME_UPDATE,
        &[PERMISSION_ROLE_MANAGE, PERMISSION_ROLE_REVOKE],
    ),
    (ROUTE_ROLE_NAME_DELETE, &[PERMISSION_ROLE_MANAGE]),
];
