# qkun 2026.3.17
server {
    listen 80;
    listen [::]:80;
    server_tokens off;
    server_name localhost;
    return 301 https://$host$request_uri;
}

server {
    server_name localhost;
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
#     gzip_static on;
#
#     sendfile on;
#     tcp_nopush on;
#     tcp_nodelay on;
#     open_file_cache max=1024 inactive=128s;
#     open_file_cache_valid 32s;
#     open_file_cache_min_uses 1;
#     keepalive_timeout 16s;
#     keepalive_requests 1024;

    ssl_protocols TLSv1.3;
    server_tokens off;
    ssl_certificate C:/Users/qkun/Desktop/nail/backend/self_signed_certs/cert.pem;
    ssl_certificate_key C:/Users/qkun/Desktop/nail/backend/self_signed_certs/key.pem;

    if ($request_method !~ ^(GET|HEAD|POST)$ ) {
        return 405;
    }

    location / {
        root C:/Users/qkun/Desktop/nail/frontend/build;
        index index.html;
        try_files $uri /index.html;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location /api/ {
        proxy_pass http://localhost:35000/;
        proxy_http_version 2;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Cache-Control "no-store";
    }
}